import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "getting-started",
    {
      type: "category",
      label: "Hooks",
      link: {
        type: "generated-index",
        slug: "/hooks",
        description:
          "Live, editable demos and full API reference for every hook in @altalyst/hookify.",
      },
      items: [{ type: "autogenerated", dirName: "hooks" }],
    },
  ],
  // Generated entirely by `docusaurus-plugin-typedoc` from the library's
  // public API surface (see docusaurus.config.ts). Do not hand-edit.
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
