name: CI

on:
  push:
    branches:
      - main

env:
  IS_FORK: ${{ github.repository != '@altalyst/hookify' }}

jobs:
  build-and-publish:
    if: env.IS_FORK == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm run setup

      - name: Run library tests
        run: npm run test
        env:
          CI: true

      - name: Build library
        run: npm run build

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Bump version and push changes
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
        with:
          minor-wording: "feat"
          major-wording: "BREAKING CHANGE"
          commit-message: "ci: bump version to {{version}}"

      - name: Publish to NPM
        if: github.ref == 'refs/heads/main' # Ensure this only runs on the main branch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish
